// Coordiation registry · Solar Linear · 480 Design · CC BY 4.0.
const names = new Set([
  "dashboard",
  "posts",
  "pages",
  "media",
  "comments",
  "themes",
  "plugins",
  "users",
  "settings",
  "tools",
  "plus",
  "arrow",
  "edit",
  "trash",
  "eye",
  "upload",
  "download",
  "menu",
  "tag",
  "clock",
  "check",
  "close",
  "paragraph",
  "heading",
  "quote",
  "list",
  "code",
  "divider",
  "button",
  "html",
  "logout",
  "up",
  "down",
  "external",
  "back",
  "spark",
]);
export const icon = (name) =>
  `<span class="icon co-icon co-icon-${names.has(name) ? name : "posts"}" aria-hidden="true"></span>`;
