import type { Metadata } from "next";
import Link from "@/app/_components/SiteLink";
import SolarIcon from "@/app/_components/SolarIcon";
import { createSeoMetadata } from "@/app/seo";
import CodeBlock from "../../_components/CodeBlock";
import { CMS_VERSION, CMS_CREATE_COMMAND, CMS_INSTALL_COMMANDS } from "../../../cms/installation";
import styles from "./page.module.css";

export const metadata: Metadata = createSeoMetadata({
  path: "/docs/installation/using-cms",
  title: "Install Coordiation CMS — npm quick start and setup",
  description: "Install Coordiation CMS from npm, start a local publishing site, create your administrator account, customize themes, and prepare your own production deployment.",
});

export default function UsingCMSPage() {
  return <article className={`docs-article ${styles.article}`}>
    <div className="docs-breadcrumb"><Link href="/docs">Docs</Link><b>/</b><span>Coordiation CMS</span></div>
    <p className="docs-overline">INSTALLATION · COORDIATION CMS</p>
    <h1>Install Coordiation CMS</h1>
    <p className="docs-lead">Start a self-hosted publishing workspace with posts, pages, a block editor, SEO controls, and native themes. The npm initializer gives you the application source in your own directory.</p>
    <div className="docs-callout"><strong>Published on npm · {CMS_VERSION} · MIT</strong><p>This guide targets CMS {CMS_VERSION}, built on Coordiation Fullstack alpha. Node.js 22.18 or newer is required; Node.js 24 is recommended. WordPress PHP themes and plugins are not compatible.</p><a href="https://www.npmjs.com/package/coordiation-cms" target="_blank" rel="noopener noreferrer">View the npm package <SolarIcon name="arrow-to-top-right" size={15} /></a></div>
    <section id="quick-start" className={styles.details}><h2>Quick start</h2><p>Run these commands in a terminal. Choose a new folder name if <code>my-site</code> already exists.</p><CodeBlock title="Create and run your CMS" code={CMS_INSTALL_COMMANDS} /><p>Then open <a href="http://127.0.0.1:3118/login" target="_blank" rel="noopener noreferrer">http://127.0.0.1:3118/login</a> on the same computer to create your first administrator.</p></section>
    <section id="create-project" className="guide-step"><div className="step-number">01</div><div><h2>Create your project</h2><CodeBlock title="Create a new directory" code={CMS_CREATE_COMMAND} /><p>The initializer copies source, public assets, scripts, and setup documentation. It refuses existing paths and does not install dependencies or start a server. The generated project is marked private to prevent accidental npm publication.</p></div></section>
    <section id="install-and-run" className="guide-step"><div className="step-number">02</div><div><h2>Install, build, and start</h2><CodeBlock title="Run the application" code="cd my-site\nnpm install\nnpm run build\nnpm start" /><p>The server listens at <code>http://127.0.0.1:3118</code>. Keep the terminal running while using your CMS. This starts the application locally; it does not publish your site to a hosting service.</p></div></section>
    <section id="administrator" className="guide-step"><div className="step-number">03</div><div><h2>Create your administrator</h2><p>Open <code>http://127.0.0.1:3118/login</code>, enter your name and email, and choose a password of at least 15 characters. No demo credentials are bundled. Initial setup closes automatically after the first account is created.</p><p>Sign in to manage your content. The dashboard is at <code>/admin</code>; the public website is at <code>/</code>.</p></div></section>
    <section id="first-site" className="guide-step"><div className="step-number">04</div><div><h2>Make the site yours</h2><ul className="docs-list"><li><strong>Settings:</strong> update your site title, reading preferences, and comment visibility.</li><li><strong>Posts / Pages:</strong> create content, review the SEO meter, and save drafts or publish.</li><li><strong>Themes:</strong> preview or activate an included theme. For Teraform, choose <strong>Edit homepage</strong> to change its sections and motion settings.</li><li><strong>Settings → AI writing:</strong> optionally connect your own OpenAI API key. Review suggestions before applying them; API billing is separate.</li></ul><Link href="/cms#inside">See the admin screenshots <SolarIcon name="arrow-right" size={15} /></Link></div></section>
    <section id="development" className={styles.details}><h2>Editing the source</h2><p>Stop the running server with Ctrl+C before using development mode:</p><CodeBlock title="Development mode" code="npm run dev" /><p>Reload the browser after source changes rebuild. Before running the production build locally again, stop development mode and run <code>npm run build</code>, then <code>npm start</code>.</p></section>
    <section id="data" className={styles.details}><h2>Your data stays with your project</h2><p>SQLite data is created at <code>data/cms.sqlite</code>. Media, content, users, themes, and settings live in that database. If you configure OpenAI, its separate encryption key is stored beside the database. Back up both; keep private files out of Git and public web directories.</p><p>The generated project includes <code>docs/DEPLOYMENT.md</code>, <code>docs/THEMES.md</code>, and <code>docs/SEO-AND-AI.md</code> for recovery, theme packaging, and AI configuration.</p></section>
    <section id="production" className={styles.details}><h2>Deploy to your own domain</h2><p>The included Docker and Compose files are a starting point for a server with Traefik. Before deployment, replace the example domain with yours in the Compose build origin, runtime <code>CMS_ORIGIN</code>, and Traefik host rule. For a non-Docker build, also update <code>coordiation.config.json</code> so the build and runtime origins match.</p><p>Create a private <code>.env</code> from <code>.env.example</code>, set your administrator email and a random <code>CMS_SETUP_TOKEN</code>, and use HTTPS with secure cookies. Local Node commands do not automatically load <code>.env</code>; provide the environment variables to the process. Follow the complete deployment and backup guide before exposing the initial setup screen.</p><a href="https://github.com/wiryosaputraofficial/coordiationcms/blob/main/docs/DEPLOYMENT.md" target="_blank" rel="noopener noreferrer">Read the deployment guide <SolarIcon name="arrow-to-top-right" size={15} /></a></section>
    <section id="troubleshooting" className={styles.details}><h2>Troubleshooting</h2><ul className="docs-list"><li><strong>Destination already exists:</strong> choose a new folder name. The initializer intentionally avoids overwriting a site.</li><li><strong>Port 3118 is in use:</strong> stop the other local server, or change the port in both application scripts and <code>coordiation.config.json</code>. Keep <code>CMS_ORIGIN</code> aligned if set.</li><li><strong>Build missing:</strong> run <code>npm run build</code> before <code>npm start</code>.</li><li><strong>Unsupported runtime:</strong> check <code>node --version</code> and use Node.js 22.18+; Node.js 24 is recommended.</li></ul></section>
    <div className="docs-next split"><Link href="/docs"><span>Back to</span><b>All installation guides</b></Link><Link href="/cms"><span>Explore</span><b>CMS showcase <SolarIcon name="arrow-right" size={15} /></b></Link></div>
  </article>;
}
